-- migrate:up

CREATE TABLE agents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    role varchar(120) NOT NULL,
    instructions text NOT NULL,
    created_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX ix_agents_name ON agents (name);

CREATE TABLE tasks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(200) NOT NULL,
    input text NOT NULL,
    status varchar(40) NOT NULL,
    output text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

CREATE INDEX ix_tasks_status ON tasks (status);

CREATE TABLE transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id varchar(80) NOT NULL,
    customer_name varchar(160) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    currency varchar(3) NOT NULL,
    status varchar(40) NOT NULL,
    error_message text,
    created_at timestamptz NOT NULL
);

CREATE INDEX ix_transactions_created_at ON transactions (created_at);
CREATE INDEX ix_transactions_customer_name ON transactions (customer_name);
CREATE UNIQUE INDEX ix_transactions_external_id ON transactions (external_id);
CREATE INDEX ix_transactions_status ON transactions (status);

CREATE TABLE tool_calls (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tool_name varchar(120) NOT NULL,
    input jsonb NOT NULL,
    output jsonb NOT NULL,
    task_id integer NOT NULL REFERENCES tasks (id),
    agent_id integer REFERENCES agents (id),
    created_at timestamptz DEFAULT now()
);

CREATE INDEX ix_tool_calls_tool_name ON tool_calls (tool_name);

-- migrate:down

DROP INDEX IF EXISTS ix_tool_calls_tool_name;
DROP TABLE IF EXISTS tool_calls;

DROP INDEX IF EXISTS ix_transactions_status;
DROP INDEX IF EXISTS ix_transactions_external_id;
DROP INDEX IF EXISTS ix_transactions_customer_name;
DROP INDEX IF EXISTS ix_transactions_created_at;
DROP TABLE IF EXISTS transactions;

DROP INDEX IF EXISTS ix_tasks_status;
DROP TABLE IF EXISTS tasks;

DROP INDEX IF EXISTS ix_agents_name;
DROP TABLE IF EXISTS agents;
